{"version":2,"defects":{"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskSuccessfullyWithoutAssignedUser":8,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskWithAssignedUser":8,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskFailsIfUserNotFound":8,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testExceptionDuringTaskCreation":8,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testUpdateNonExistingTask":8,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testCompletedTaskCannotChangeStatus":7,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testInvalidStatusTransition":8,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testSuccessfulUpdate":7,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testRepositoryThrowsException":7},"times":{"App\\Tests\\Unit\\Domain\\Model\\TaskTest::testTaskIsCreatedWithDefaultValues":0,"App\\Tests\\Unit\\Domain\\Model\\TaskTest::testSettersAndGettersWorkCorrectly":0,"App\\Tests\\Unit\\Domain\\Model\\UserTest::testUserIsCreatedWithConstructorValues":0,"App\\Tests\\Unit\\Domain\\Model\\UserTest::testSettersAndGettersWorkCorrectly":0,"App\\Tests\\Unit\\Application\\Task\\AssignTaskToUserTest::testAssignTaskToUserSuccess":0.003,"App\\Tests\\Unit\\Application\\Task\\AssignTaskToUserTest::testTaskNotFound":0,"App\\Tests\\Unit\\Application\\Task\\AssignTaskToUserTest::testUserNotFound":0,"App\\Tests\\Unit\\Application\\Task\\AssignTaskToUserTest::testExceptionDuringAssignment":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskSuccessfullyWithoutAssignedUser":0.001,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskWithAssignedUser":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testCreateTaskFailsIfUserNotFound":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\CreateTaskUseCaseTest::testExceptionDuringTaskCreation":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\DeleteTaskUseCaseTest::testDeleteTaskSuccessfully":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\DeleteTaskUseCaseTest::testTaskNotFound":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\DeleteTaskUseCaseTest::testExceptionDuringDeletion":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\GetTaskDetailUseCaseTest::testGetTaskDetailSuccessfully":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\GetTaskDetailUseCaseTest::testTaskNotFound":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\GetTaskDetailUseCaseTest::testExceptionDuringGetTask":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\ListTaskUseCaseTest::testListTasksSuccessfullyWithoutFilters":0.001,"App\\Tests\\Unit\\Application\\UseCase\\Task\\ListTaskUseCaseTest::testListTasksSuccessfullyWithFilters":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\ListTaskUseCaseTest::testNoTasksFound":0,"App\\Tests\\Unit\\Application\\UseCase\\Task\\ListTaskUseCaseTest::testExceptionDuringListTasks":0,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testUpdateNonExistingTask":0,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testCompletedTaskCannotChangeStatus":0,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testInvalidStatusTransition":0,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testSuccessfulUpdate":0,"App\\Tests\\Application\\UseCase\\Task\\UpdateTask\\UpdateTaskUseCaseTest::testRepositoryThrowsException":0,"App\\Tests\\Unit\\Application\\UseCase\\User\\CreateUserUseCaseTest::testCreateUserSuccess":0.001,"App\\Tests\\Unit\\Application\\UseCase\\User\\CreateUserUseCaseTest::testExceptionDuringSave":0,"App\\Tests\\Unit\\Application\\UseCase\\User\\ListUserUseCaseTest::testListUsersSuccess":0,"App\\Tests\\Unit\\Application\\UseCase\\User\\ListUserUseCaseTest::testNoUsersFound":0,"App\\Tests\\Unit\\Application\\UseCase\\User\\ListUserUseCaseTest::testExceptionDuringFetch":0}}